services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://host.docker.internal:6379
      - GROQ_KEY=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
      - JWT_SECRET=${JWT_SECRET}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
    volumes:
      - ./users.db:/app/users.db
      - ./scans.db:/app/scans.db
      - ./logs:/app/logs
    networks:
      - customs-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - customs-network

networks:
  customs-network:
    driver: bridge
